spring:
  application:
    name: auto_trader
  datasource:
    url: jdbc:postgresql://localhost:5434/auto_trader_db
    username: eustache
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        dialect: org.hibernate.dialect.PostgreSQLDialect